"""Drilling-site alternative enumeration against one fixed DH interface.

## What this is, and is not

This is NOT a new enumeration algorithm. `enumerate_compatible_alternatives()`
(workflow.joint_enumeration, unmodified) already enumerates only tuples whose
route belongs to the same site as its scenario -- see that module's own
docstring. This wrapper calls it completely unchanged, against routes already
generated by `network.site_routing.generate_site_routes()` (also unmodified),
and then asserts -- defensively, as a CODE-BUG guard, never a domain outcome
-- that every returned identity's `attachment_id` equals the resolved fixed
station's own `station_id`.

That assertion can only ever fire if a caller passes routes generated from a
`routing_policy.allowed_attachment_ids` that names more than the fixed
station's one id -- which `data_contracts.fixed_interface.resolve_fixed_
integration_station()` already refuses to validate a package for
(FixedInterfaceErrorCode.STATION_AMBIGUOUS). This module's own AssertionError
is therefore unreachable under any workflow that resolves its station before
generating routes (workflow.fixed_interface_workflow does exactly that,
in that order) -- it exists as defense in depth, not as the primary gate."""
from __future__ import annotations

from ..data_contracts.fixed_interface import FixedHeatIntegrationStation
from ..data_contracts.joint_study import AlternativeIdentity, JointStudyPackage, SiteConnectionRoute
from .joint_enumeration import enumerate_compatible_alternatives, possible_combination_count

__all__ = ["enumerate_drilling_site_alternatives", "possible_combination_count"]


def enumerate_drilling_site_alternatives(
    package: JointStudyPackage, routes: list[SiteConnectionRoute], station: FixedHeatIntegrationStation,
) -> list[AlternativeIdentity]:
    """Every returned `AlternativeIdentity.surface_site_id` is a candidate
    DRILLING SITE; every returned `AlternativeIdentity.attachment_id` is
    the SAME fixed `station.station_id` -- the corrected candidate
    identity `i=(s,g)` with `a=a0` (task's own formulation), expressed
    through the existing six-field `AlternativeIdentity` with one field
    pinned rather than a new, narrower identity type (ARCH-002-style
    reuse: every downstream consumer of `AlternativeIdentity` -- economics,
    decision, rendering -- keeps working unchanged)."""
    identities = enumerate_compatible_alternatives(package, routes)
    for identity in identities:
        assert identity.attachment_id == station.station_id, (
            f"fixed-interface invariant violated: alternative {identity.alternative_id!r} has "
            f"attachment_id={identity.attachment_id!r}, expected the fixed station's own "
            f"{station.station_id!r} -- this indicates routes were generated from a "
            "routing_policy.allowed_attachment_ids not already validated by "
            "resolve_fixed_integration_station()"
        )
    return identities
